### ISSUE TITLE
Freeze schema for 1.0

### ISSUE THREAD

**Issue by laurenkt** [JackoRo/SWEngPWS#11]
I propose we freeze the schema as of 21faabf (the rules rather than the annotations) and call that version 1.0 of the PWS.

Any further revisions to the actual schema can be part of a 1.1 proposal to be agreed by all groups.

If you agree could you post a comment confirming so we can have a record of all groups signing off.

**Comment by AmyJoT** [comment]
Confirmed!

**Comment by SB800046** [comment]
I agree to the proposal

**Comment by BenKing6** [comment]
I agree

**Comment by JackoRo** [comment]
One second. Need to make one last change to it.

**Comment by zwrawr** [comment]
I'm happy with what we have!

**Comment by JackoRo** [comment]
Ok all done.
