### ISSUE TITLE
Add documentation annotations

### ISSUE THREAD

**Issue by laurenkt** [JackoRo/SWEngPWS#5]
Self-explanatory

**Comment by JackoRo** [comment]
Is more required? Sorry I was busy yesterday so I couldn't really add much to it.

**Comment by laurenkt** [comment]
Yeah we need to do the documentation annotations for every element / type / attribute group

**Comment by JackoRo** [comment]
Ok. I'll have to wait until I get home to add more stuff. Does it need to be done at the end of today?

**Comment by laurenkt** [comment]
I think so, or by the end of tomorrow anyway, but I'm sure others will chip in too !
